---
# tasks file for roles/ubuntu_docker

- name: Install Pre-Requisites
  apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Install Docker File
  apt:
    name: docker.io
    state: latest
    update_cache: yes
  register: docker

- name: Install docker.py
  pip:
    name: docker.py
    state: latest
  when: docker.changed
